<?php

/**
 * @file
 * This module exposes the Mobile Commons API.
 */

/**
 * Implements hook_libraries_info().
 */
function mobilecommons_libraries_info() {
  $libraries['mobilecommons'] = array(
    'name' => 'Mobile Commons PHP',
    'vendor url' => 'http://www.mobilecommons.com/mobile-commons-api',
    'download url' => 'https://github.com/DoSomething/mobilecommons-php/archive/master.zip',
    'files' => array(
      'php' => array('lib/MobileCommons.php'),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_menu().
 */
function mobilecommons_menu() {
   $items['admin/content'] = array(
    'title' => 'Mobile Commons settings',
    'description' => 'Manage Mobile Commons settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mobilecommons_config_form'),
    'access arguments' => array('administer mobilecommons'),
    'file' => 'mobilecommons.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function mobilecommons_permission() {
  return array(
    'administer mobilecommons' =>  array(
    'title' => t('Administer Mobile Commons'),
    'description' => t('Manage Mobile Commons settings.'),
  );
}

